services:
  db:
    image: postgres:15-alpine
    container_name: smart-expense-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_expense_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: smart-expense-tracker:latest
    container_name: expense_tracker_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smart_expense_tracker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
volumes:
  postgres_data: