spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_expense_tracker_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 900000 # 15 хвилин у мілісекундах (Access Token)
      refresh-token:
        expiration: 604800000 # 7 днів (Refresh Token)